/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

//import clases
import Clases.Administrador;
import Clases.AlmacenDatos;
import Clases.AsesorVenta;
import Clases.Empleado;
//import looks
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JButton;

/**
 *
 * @author LUCAS
 */
public class Interfaz_Main extends javax.swing.JFrame {
    private int mouseX;
    private int mouseY;
    private boolean maximized = true;
    private Empleado empleadoActual;
    private AlmacenDatos ad;
    
    public Interfaz_Main() {
        initComponents();
        this.ad = new AlmacenDatos();
        for (JButton s : new JButton[]{btnMinimizar, btnMaximizar, btnCerrar}) {
            s.setContentAreaFilled(false);
            s.setBorderPainted(false);
            s.setFocusPainted(false);
            s.setOpaque(true);
            s.setBackground(new Color(30, 30, 40));
            s.setForeground(Color.WHITE);
        }
        for (JButton bl : new JButton[]{btnEmpleados, btnProyectos, btnAcabados, btnClientes, btnReservaciones, btnVentas, btnReportes, btnLogout}) {
            bl.setContentAreaFilled(false);
            bl.setBorderPainted(false);
            bl.setFocusPainted(false);
            bl.setOpaque(true);
            bl.setBackground(new Color(26,26,34));
            bl.setForeground(Color.WHITE);
        }
        
        setExtendedState(Interfaz_Main.MAXIMIZED_BOTH);
        getContentPane().setBackground(new Color(18, 18, 24));
    }
    public Interfaz_Main(AlmacenDatos ad, Empleado empleadoActual) {
        initComponents();

        this.ad = ad;
        this.empleadoActual = empleadoActual;

        for (JButton s : new JButton[]{btnMinimizar, btnMaximizar, btnCerrar}) {
            s.setContentAreaFilled(false);
            s.setBorderPainted(false);
            s.setFocusPainted(false);
            s.setOpaque(true);
            s.setBackground(new Color(30, 30, 40));
            s.setForeground(Color.WHITE);
        }

        for (JButton bl : new JButton[]{btnEmpleados, btnProyectos, btnAcabados, btnClientes, btnReservaciones, btnVentas, btnReportes, btnLogout}) {
            bl.setContentAreaFilled(false);
            bl.setBorderPainted(false);
            bl.setFocusPainted(false);
            bl.setOpaque(true);
            bl.setBackground(new Color(26, 26, 34));
            bl.setForeground(Color.WHITE);
        }

        setExtendedState(Interfaz_Main.MAXIMIZED_BOTH);
        getContentPane().setBackground(new Color(18, 18, 24));
    }
    
    private boolean esAdministrador() {
        if (empleadoActual == null) {
            return false;
        }

        if (empleadoActual instanceof Administrador) {
            return true;
        }

        return empleadoActual.getRol() != null
                && empleadoActual.getRol().equalsIgnoreCase("Administrador");
    }
    
    private boolean esAsesorVenta() {
        if (empleadoActual == null) {
            return false;
        }

        if (empleadoActual instanceof AsesorVenta) {
            return true;
        }

        return empleadoActual.getRol() != null
                && empleadoActual.getRol().equalsIgnoreCase("Asesor de Venta");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBorde = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        pnlSidebar = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnProyectos = new javax.swing.JButton();
        btnAcabados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnReservaciones = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlCuerpo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 18, 25));
        setUndecorated(true);

        pnlBorde.setBackground(new java.awt.Color(30, 30, 40));
        pnlBorde.setForeground(new java.awt.Color(255, 255, 255));
        pnlBorde.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlBordeMouseDragged(evt);
            }
        });
        pnlBorde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBordeMousePressed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Main");

        btnCerrar.setBackground(new java.awt.Color(30, 30, 40));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMaximizar.setBackground(new java.awt.Color(30, 30, 40));
        btnMaximizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMaximizar.setText("❐");
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseExited(evt);
            }
        });
        btnMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizarActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(30, 30, 40));
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setText("—");
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBordeLayout = new javax.swing.GroupLayout(pnlBorde);
        pnlBorde.setLayout(pnlBordeLayout);
        pnlBordeLayout.setHorizontalGroup(
            pnlBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 830, Short.MAX_VALUE)
                .addComponent(btnMinimizar)
                .addGap(0, 0, 0)
                .addComponent(btnMaximizar)
                .addGap(0, 0, 0)
                .addComponent(btnCerrar))
        );
        pnlBordeLayout.setVerticalGroup(
            pnlBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordeLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMaximizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSidebar.setBackground(new java.awt.Color(26, 26, 34));
        pnlSidebar.setForeground(new java.awt.Color(255, 255, 255));

        btnEmpleados.setText("Empleados");
        btnEmpleados.setToolTipText("");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnProyectos.setText("Proyectos");
        btnProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectosActionPerformed(evt);
            }
        });

        btnAcabados.setText("Acabados");
        btnAcabados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcabadosActionPerformed(evt);
            }
        });

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnReservaciones.setText("Reservaciones");
        btnReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservacionesActionPerformed(evt);
            }
        });

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAcabados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAcabados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
        );

        pnlCuerpo.setBackground(new java.awt.Color(18, 18, 24));
        pnlCuerpo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCuerpoLayout = new javax.swing.GroupLayout(pnlCuerpo);
        pnlCuerpo.setLayout(pnlCuerpoLayout);
        pnlCuerpoLayout.setHorizontalGroup(
            pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCuerpoLayout.setVerticalGroup(
            pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBorde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBordeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBordeMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_pnlBordeMousePressed

    private void pnlBordeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBordeMouseDragged
        setLocation(
            evt.getXOnScreen() - mouseX,
            evt.getYOnScreen() - mouseY
        );
    }//GEN-LAST:event_pnlBordeMouseDragged

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        btnCerrar.setBackground(new Color(30, 30, 40));
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        btnCerrar.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizarActionPerformed
        if (maximized) {
        setExtendedState(Interfaz_Main.NORMAL);
        btnMaximizar.setText("□");
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
        maximized = false;
        setLocationRelativeTo(null);
    } else {
        setExtendedState(Interfaz_Main.MAXIMIZED_BOTH);
        btnMaximizar.setText("❐");
        setShape (null);
        maximized = true;
    }
    }//GEN-LAST:event_btnMaximizarActionPerformed
    
    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        setState(Interfaz_Main.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseEntered
        btnMaximizar.setBackground(new Color(60, 60, 75));
    }//GEN-LAST:event_btnMaximizarMouseEntered

    private void btnMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseExited
        btnMaximizar.setBackground(new Color(30, 30, 40));
    }//GEN-LAST:event_btnMaximizarMouseExited

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        btnMinimizar.setBackground(new Color(60, 60, 75));
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        btnMinimizar.setBackground(new Color(30, 30, 40));
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        if (!esAdministrador()) {
        JOptionPane.showMessageDialog(
                this,
                "Acceso denegado. Solo los administradores pueden entrar a Empleados.",
                "Sin permisos",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

        pnlCuerpo.removeAll();
        pnlEmpleados panel = new pnlEmpleados(ad);
        panel.setSize(pnlCuerpo.getSize());
        panel.setLocation(0, 0);
        pnlCuerpo.setLayout(new java.awt.BorderLayout());
        pnlCuerpo.add(panel, java.awt.BorderLayout.CENTER);
        pnlCuerpo.revalidate();
        pnlCuerpo.repaint();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectosActionPerformed
        if (!esAdministrador()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Acceso denegado. Solo los administradores pueden entrar a Proyectos.",
                "Sin permisos",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
        return;
        }

        pnlCuerpo.removeAll();

        pnlProyectos panel = new pnlProyectos(ad, pnlCuerpo);
        panel.setSize(pnlCuerpo.getSize());
        panel.setLocation(0, 0);

        pnlCuerpo.setLayout(new java.awt.BorderLayout());
        pnlCuerpo.add(panel, java.awt.BorderLayout.CENTER);

        pnlCuerpo.revalidate();
        pnlCuerpo.repaint();
    }//GEN-LAST:event_btnProyectosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        if (!esAsesorVenta()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Acceso denegado. Solo los asesores de venta pueden entrar a Clientes.",
                    "Sin permisos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        pnlCuerpo.removeAll();

        pnlClientes panel = new pnlClientes(ad);
        panel.setSize(pnlCuerpo.getSize());
        panel.setLocation(0, 0);

        pnlCuerpo.setLayout(new java.awt.BorderLayout());
        pnlCuerpo.add(panel, java.awt.BorderLayout.CENTER);

        pnlCuerpo.revalidate();
        pnlCuerpo.repaint();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnAcabadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcabadosActionPerformed
        if (!esAsesorVenta()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Acceso denegado. Solo los asesores de venta pueden entrar a Acabados.",
                    "Sin permisos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        pnlCuerpo.removeAll();

        pnlAcabados panel = new pnlAcabados(ad);
        panel.setSize(pnlCuerpo.getSize());
        panel.setLocation(0, 0);

        pnlCuerpo.setLayout(new java.awt.BorderLayout());
        pnlCuerpo.add(panel, java.awt.BorderLayout.CENTER);

        pnlCuerpo.revalidate();
        pnlCuerpo.repaint();
    }//GEN-LAST:event_btnAcabadosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        if (!esAsesorVenta()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Acceso denegado. Solo los asesores de venta pueden entrar a Ventas.",
                    "Sin permisos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        pnlCuerpo.removeAll();

        pnlVentas panel = new pnlVentas(ad, (AsesorVenta) empleadoActual);
        panel.setSize(pnlCuerpo.getSize());
        panel.setLocation(0, 0);

        pnlCuerpo.setLayout(new java.awt.BorderLayout());
        pnlCuerpo.add(panel, java.awt.BorderLayout.CENTER);

        pnlCuerpo.revalidate();
        pnlCuerpo.repaint();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservacionesActionPerformed
        if (!esAsesorVenta()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Acceso denegado. Solo los asesores de venta pueden entrar a Reservaciones.",
                    "Sin permisos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        pnlCuerpo.removeAll();

        pnlReservas panel = new pnlReservas(ad);
        panel.setSize(pnlCuerpo.getSize());
        panel.setLocation(0, 0);

        pnlCuerpo.setLayout(new java.awt.BorderLayout());
        pnlCuerpo.add(panel, java.awt.BorderLayout.CENTER);

        pnlCuerpo.revalidate();
        pnlCuerpo.repaint();
    }//GEN-LAST:event_btnReservacionesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Interfaz_Login login = new Interfaz_Login(ad);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcabados;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnProyectos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReservaciones;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBorde;
    private javax.swing.JPanel pnlCuerpo;
    private javax.swing.JPanel pnlSidebar;
    // End of variables declaration//GEN-END:variables
}
