/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

//imports de clases
import Clases.Acabados;
import Clases.AlmacenDatos;
import Clases.Departamento;
import Clases.Proyecto;
//imports para popup de añadido
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
//imports para modo oscuro
import java.awt.Color;
import java.awt.Font;
//imports para tabla
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author LUCAS
 */
public class pnlAcabados extends javax.swing.JPanel {
    private AlmacenDatos ad;
    private ArrayList<Proyecto> proyectosMostrados = new ArrayList<>();
    private ArrayList<Departamento> departamentosMostrados = new ArrayList<>();
    private Departamento departamentoSeleccionado;
    public pnlAcabados(AlmacenDatos ad) {
        initComponents();
        this.ad = ad;
        configurarTabla();
        aplicarTemaOscuro();
        cargarProyectos();

        cmbProyectos.addActionListener(e -> cargarDepartamentosDelProyecto());
        cmbDepartamentos.addActionListener(e -> actualizarAcabados());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcabados = new javax.swing.JLabel();
        lblProyecto = new javax.swing.JLabel();
        btnNuevoAcabado = new javax.swing.JButton();
        scrlAcabados = new javax.swing.JScrollPane();
        tblAcabados = new javax.swing.JTable();
        cmbProyectos = new javax.swing.JComboBox<>();
        lblDepartamento = new javax.swing.JLabel();
        cmbDepartamentos = new javax.swing.JComboBox<>();
        lblPrecioBase = new javax.swing.JLabel();
        lblPrecioFinal = new javax.swing.JLabel();
        lblPrecioBaseValor = new javax.swing.JLabel();
        lblPrecioFinalValor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(18, 18, 24));

        lblAcabados.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblAcabados.setForeground(new java.awt.Color(255, 255, 255));
        lblAcabados.setText("Acabados");

        lblProyecto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblProyecto.setForeground(new java.awt.Color(255, 255, 255));
        lblProyecto.setText("Proyecto:");

        btnNuevoAcabado.setBackground(new java.awt.Color(45, 45, 55));
        btnNuevoAcabado.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNuevoAcabado.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoAcabado.setText("Agregar Acabado +");
        btnNuevoAcabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAcabadoActionPerformed(evt);
            }
        });

        scrlAcabados.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        tblAcabados.setBackground(new java.awt.Color(45, 45, 45));
        tblAcabados.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblAcabados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Usuario", "Contraseña", "Rol"
            }
        ));
        tblAcabados.getTableHeader().setResizingAllowed(false);
        tblAcabados.getTableHeader().setReorderingAllowed(false);
        scrlAcabados.setViewportView(tblAcabados);

        cmbProyectos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblDepartamento.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartamento.setText("Departamento:");

        cmbDepartamentos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblPrecioBase.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPrecioBase.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioBase.setText("Precio Base:");

        lblPrecioFinal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPrecioFinal.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioFinal.setText("Precio Final:");

        lblPrecioBaseValor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPrecioBaseValor.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioBaseValor.setText("S/. 0.0");

        lblPrecioFinalValor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPrecioFinalValor.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioFinalValor.setText("S/. 0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlAcabados, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDepartamento)
                                .addComponent(lblProyecto))
                            .addComponent(lblAcabados)
                            .addComponent(lblPrecioBase)
                            .addComponent(lblPrecioFinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecioBaseValor)
                                    .addComponent(lblPrecioFinalValor))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbProyectos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbDepartamentos, 0, 225, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevoAcabado)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcabados)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProyecto)
                    .addComponent(cmbProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamento)
                    .addComponent(cmbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoAcabado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrecioBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecioFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrlAcabados, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrecioBaseValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecioFinalValor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoAcabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAcabadoActionPerformed
        abrirFormularioNuevoAcabado();
    }//GEN-LAST:event_btnNuevoAcabadoActionPerformed
    
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre",
                    "Descripción",
                    "Precio adicional"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblAcabados.setModel(modelo);
    }

    private void cargarProyectos() {
        cmbProyectos.removeAllItems();
        proyectosMostrados.clear();

        if (ad == null) {
            return;
        }

        Proyecto[] proyectos = ad.getProyectos();

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                proyectosMostrados.add(proy);
                cmbProyectos.addItem(proy.getNombreProyecto());
            }
        }

        cargarDepartamentosDelProyecto();
    }

    private void cargarDepartamentosDelProyecto() {
        cmbDepartamentos.removeAllItems();
        departamentosMostrados.clear();
        departamentoSeleccionado = null;

        int indiceProyecto = cmbProyectos.getSelectedIndex();

        if (indiceProyecto < 0 || indiceProyecto >= proyectosMostrados.size()) {
            actualizarAcabados();
            return;
        }

        Proyecto proyecto = proyectosMostrados.get(indiceProyecto);
        Departamento[] departamentos = proyecto.getDepartamentos();

        for (int i = 0; i < proyecto.getContadorDepartamentos(); i++) {
            Departamento dep = departamentos[i];

            if (dep != null && !dep.getEstado().equalsIgnoreCase("Vendido")) {
                departamentosMostrados.add(dep);

                cmbDepartamentos.addItem(
                        "Depa " + dep.getNumDepa()
                        + " | Código: " + dep.getCodigoUnico()
                        + " | Estado: " + dep.getEstado()
                );
            }
        }

        actualizarAcabados();
    }

    private void actualizarAcabados() {
        DefaultTableModel modelo = (DefaultTableModel) tblAcabados.getModel();
        modelo.setRowCount(0);

        int indiceDep = cmbDepartamentos.getSelectedIndex();

        if (indiceDep < 0 || indiceDep >= departamentosMostrados.size()) {
            departamentoSeleccionado = null;
            lblPrecioBaseValor.setText("S/ 0.00");
            lblPrecioFinalValor.setText("S/ 0.00");
            return;
        }

        departamentoSeleccionado = departamentosMostrados.get(indiceDep);

        Acabados[] acabados = departamentoSeleccionado.getAcabados();

        for (int i = 0; i < departamentoSeleccionado.getContadorAcabados(); i++) {
            Acabados acabado = acabados[i];

            if (acabado != null) {
                modelo.addRow(new Object[]{
                    acabado.getNombre(),
                    acabado.getDescripcion(),
                    acabado.getPrecioAdicional()
                });
            }
        }

        lblPrecioBaseValor.setText(
                "S/ " + String.format("%.2f", departamentoSeleccionado.getPrecioVenta())
        );

        lblPrecioFinalValor.setText(
                "S/ " + String.format("%.2f", departamentoSeleccionado.calcularPrecioFinal())
        );
    }

    private void abrirFormularioNuevoAcabado() {
        if (departamentoSeleccionado == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un departamento.",
                    "Sin departamento",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (departamentoSeleccionado.getEstado().equalsIgnoreCase("Vendido")) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pueden agregar acabados a un departamento vendido.",
                    "Departamento vendido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (departamentoSeleccionado.getContadorAcabados() >= departamentoSeleccionado.getAcabados().length) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pueden agregar más acabados a este departamento.",
                    "Límite alcanzado",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        JTextField txtNombre = new JTextField();
        JTextField txtDescripcion = new JTextField();
        JTextField txtPrecio = new JTextField();

        Object[] formulario = {
            "Nombre:", txtNombre,
            "Descripción:", txtDescripcion,
            "Precio adicional:", txtPrecio
        };

        int opcion = JOptionPane.showConfirmDialog(
                this,
                formulario,
                "Nuevo Acabado",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String nombre = txtNombre.getText().trim();
            String descripcion = txtDescripcion.getText().trim();
            String precioTexto = txtPrecio.getText().trim();

            if (nombre.isEmpty() || descripcion.isEmpty() || precioTexto.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            double precioAdicional;

            try {
                precioAdicional = Double.parseDouble(precioTexto);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "El precio adicional debe ser numérico.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (precioAdicional <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "El precio adicional debe ser mayor que 0.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            Acabados nuevo = new Acabados(
                    nombre,
                    descripcion,
                    precioAdicional
            );

            departamentoSeleccionado.agregarAcabado(nuevo);

            actualizarAcabados();

            JOptionPane.showMessageDialog(
                    this,
                    "Acabado agregado correctamente.\n\nNuevo precio final: S/ "
                    + String.format("%.2f", departamentoSeleccionado.calcularPrecioFinal())
            );
        }
    }
    
        private void aplicarTemaOscuro() {
            Color fondoTabla = new Color(45, 45, 45);
            Color fondoHeader = new Color(35, 35, 35);
            Color texto = Color.WHITE;
            Color seleccion = new Color(0, 120, 215);
            Color grid = new Color(70, 70, 70);

            setBackground(new Color(18, 18, 24));

            tblAcabados.setBackground(fondoTabla);
            tblAcabados.setForeground(texto);
            tblAcabados.setGridColor(grid);
            tblAcabados.setSelectionBackground(seleccion);
            tblAcabados.setSelectionForeground(texto);
            tblAcabados.setRowHeight(26);
            tblAcabados.setFillsViewportHeight(true);

            scrlAcabados.getViewport().setBackground(fondoTabla);
            scrlAcabados.setBorder(javax.swing.BorderFactory.createLineBorder(grid));

            JTableHeader header = tblAcabados.getTableHeader();
            header.setBackground(fondoHeader);
            header.setForeground(texto);
            header.setFont(new Font("Calibri", Font.BOLD, 12));
            header.setReorderingAllowed(false);

            tblAcabados.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(
                        javax.swing.JTable table,
                        Object value,
                        boolean isSelected,
                        boolean hasFocus,
                        int row,
                        int column) {

                    java.awt.Component c = super.getTableCellRendererComponent(
                            table, value, isSelected, hasFocus, row, column);

                    if (isSelected) {
                        c.setBackground(seleccion);
                    } else {
                        c.setBackground(fondoTabla);
                    }

                    c.setForeground(texto);
                    return c;
                }
            });

            header.setDefaultRenderer(new DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(
                        javax.swing.JTable table,
                        Object value,
                        boolean isSelected,
                        boolean hasFocus,
                        int row,
                        int column) {

                    java.awt.Component c = super.getTableCellRendererComponent(
                            table, value, isSelected, hasFocus, row, column);

                    c.setBackground(fondoHeader);
                    c.setForeground(texto);
                    c.setFont(new Font("Calibri", Font.BOLD, 12));

                    return c;
                }
            });
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoAcabado;
    private javax.swing.JComboBox<String> cmbDepartamentos;
    private javax.swing.JComboBox<String> cmbProyectos;
    private javax.swing.JLabel lblAcabados;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblPrecioBase;
    private javax.swing.JLabel lblPrecioBaseValor;
    private javax.swing.JLabel lblPrecioFinal;
    private javax.swing.JLabel lblPrecioFinalValor;
    private javax.swing.JLabel lblProyecto;
    private javax.swing.JScrollPane scrlAcabados;
    private javax.swing.JTable tblAcabados;
    // End of variables declaration//GEN-END:variables
}

