/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

//imports de clases
import Clases.AlmacenDatos;
import Clases.Cliente;
//imports para popup de añadido
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
//imports para modo oscuro
import java.awt.Color;
import java.awt.Font;
//imports para tabla
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author LUCAS
 */
public class pnlClientes extends javax.swing.JPanel {
    private AlmacenDatos ad;
    public pnlClientes(AlmacenDatos ad) {
        initComponents();

        this.ad = ad;

        configurarTabla();
        aplicarTemaOscuro();
        cargarTabla();

        txtBuscar.addActionListener(e -> buscarClientes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClientes = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        scrlClientes = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(18, 18, 24));

        lblClientes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setText("Clientes");

        lblBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar:");

        txtBuscar.setBackground(new java.awt.Color(30, 30, 40));
        txtBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(45, 45, 55));
        btnBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevoCliente.setBackground(new java.awt.Color(45, 45, 55));
        btnNuevoCliente.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("Nuevo Cliente +");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        scrlClientes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        tblClientes.setBackground(new java.awt.Color(45, 45, 45));
        tblClientes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Usuario", "Contraseña", "Rol"
            }
        ));
        tblClientes.getTableHeader().setResizingAllowed(false);
        tblClientes.getTableHeader().setReorderingAllowed(false);
        scrlClientes.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevoCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClientes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        abrirFormularioNuevoCliente();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarClientes();
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "DNI",
                    "Nombres",
                    "Apellidos",
                    "Nacimiento",
                    "Estado Civil",
                    "Ocupación",
                    "Ingresos",
                    "Teléfono",
                    "Correo"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblClientes.setModel(modelo);
    }

    private void cargarTabla() {
        cargarTabla("");
    }

    private void buscarClientes() {
        String textoBusqueda = txtBuscar.getText().trim();
        cargarTabla(textoBusqueda);
    }

    private void cargarTabla(String filtro) {
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);

        if (ad == null) {
            return;
        }

        String busqueda = filtro.toLowerCase();

        Cliente[] clientes = ad.getClientes();

        for (int i = 0; i < ad.getContClientes(); i++) {
            Cliente cli = clientes[i];

            if (cli != null) {
                String dni = cli.getDni();
                String nombres = cli.getNombres();
                String apellidos = cli.getApellidos();
                String estadoCivil = cli.getEstadoCivil();
                String ocupacion = cli.getOcupacion();
                String telefono = cli.getTelefono();
                String correo = cli.getCorreo();

                boolean coincide =
                        busqueda.isEmpty()
                        || dni.toLowerCase().contains(busqueda)
                        || nombres.toLowerCase().contains(busqueda)
                        || apellidos.toLowerCase().contains(busqueda)
                        || estadoCivil.toLowerCase().contains(busqueda)
                        || ocupacion.toLowerCase().contains(busqueda)
                        || telefono.toLowerCase().contains(busqueda)
                        || correo.toLowerCase().contains(busqueda);

                if (coincide) {
                    modelo.addRow(new Object[]{
                        cli.getDni(),
                        cli.getNombres(),
                        cli.getApellidos(),
                        cli.getFechaNacimiento(),
                        cli.getEstadoCivil(),
                        cli.getOcupacion(),
                        cli.getIngresosMensuales(),
                        cli.getTelefono(),
                        cli.getCorreo()
                    });
                }
            }
        }
    }
    private void abrirFormularioNuevoCliente() {
        if (ad == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: no se encontró el almacén de datos.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (ad.getContClientes() >= ad.getClientes().length) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pueden agregar más clientes.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        JTextField txtDni = new JTextField();
        JTextField txtNombres = new JTextField();
        JTextField txtApellidos = new JTextField();
        JTextField txtNacimiento = new JTextField();
        JTextField txtOcupacion = new JTextField();
        JTextField txtIngresos = new JTextField();
        JTextField txtTelefono = new JTextField();
        JTextField txtCorreo = new JTextField();

        JComboBox<String> cmbEstadoCivil = new JComboBox<>(new String[]{
            "Soltero",
            "Casado",
            "Divorciado",
            "Viudo"
        });

        Object[] formulario = {
            "DNI:", txtDni,
            "Nombres:", txtNombres,
            "Apellidos:", txtApellidos,
            "Fecha nacimiento:", txtNacimiento,
            "Estado civil:", cmbEstadoCivil,
            "Ocupación:", txtOcupacion,
            "Ingresos mensuales:", txtIngresos,
            "Teléfono:", txtTelefono,
            "Correo:", txtCorreo
        };

        int opcion = JOptionPane.showConfirmDialog(
                this,
                formulario,
                "Nuevo Cliente",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String dni = txtDni.getText().trim();
            String nombres = txtNombres.getText().trim();
            String apellidos = txtApellidos.getText().trim();
            String nacimiento = txtNacimiento.getText().trim();
            String estadoCivil = cmbEstadoCivil.getSelectedItem().toString();
            String ocupacion = txtOcupacion.getText().trim();
            String ingresosTexto = txtIngresos.getText().trim();
            String telefono = txtTelefono.getText().trim();
            String correo = txtCorreo.getText().trim();

            if (dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty()
                    || nacimiento.isEmpty() || ocupacion.isEmpty()
                    || ingresosTexto.isEmpty() || telefono.isEmpty()
                    || correo.isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            double ingresos;

            try {
                ingresos = Double.parseDouble(ingresosTexto);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Los ingresos mensuales deben ser numéricos.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            Cliente nuevo = new Cliente(
                    dni,
                    nombres,
                    apellidos,
                    nacimiento,
                    estadoCivil,
                    ocupacion,
                    ingresos,
                    telefono,
                    correo
            );

            Cliente[] clientes = ad.getClientes();
            clientes[ad.getContClientes()] = nuevo;
            ad.setContClientes(ad.getContClientes() + 1);

            cargarTabla();

            JOptionPane.showMessageDialog(
                    this,
                    "Cliente agregado correctamente."
            );
        }
    }
    
    private void aplicarTemaOscuro() {
        Color fondoTabla = new Color(45, 45, 45);
        Color fondoHeader = new Color(35, 35, 35);
        Color texto = Color.WHITE;
        Color seleccion = new Color(0, 120, 215);
        Color grid = new Color(70, 70, 70);
        txtBuscar.setForeground(Color.WHITE);
        txtBuscar.setCaretColor(Color.WHITE);
        tblClientes.setOpaque(true);
        tblClientes.setFillsViewportHeight(true);
        tblClientes.setBackground(fondoTabla);
        tblClientes.setForeground(texto);
        tblClientes.setGridColor(grid);
        tblClientes.setSelectionBackground(seleccion);
        tblClientes.setSelectionForeground(texto);
        tblClientes.setRowHeight(26);
        scrlClientes.setBackground(fondoTabla);
        scrlClientes.getViewport().setOpaque(true);
        scrlClientes.getViewport().setBackground(fondoTabla);
        scrlClientes.setBorder(javax.swing.BorderFactory.createLineBorder(grid));
        JTableHeader header = tblClientes.getTableHeader();
        header.setOpaque(true);
        header.setBackground(fondoHeader);
        header.setForeground(texto);
        header.setFont(new Font("Calibri", Font.BOLD, 12));
        header.setReorderingAllowed(false);
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(fondoHeader);
                c.setForeground(texto);
                c.setFont(new Font("Calibri", Font.BOLD, 12));

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                setHorizontalAlignment(CENTER);

                return c;
            }
        });

        tblClientes.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table,
                    Object value,boolean isSelected,boolean hasFocus,int row,int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value,isSelected,hasFocus,row,column);

                if (isSelected) {
                    c.setBackground(seleccion);
                    c.setForeground(texto);
                } else {
                    c.setBackground(fondoTabla);
                    c.setForeground(texto);
                }

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                return c;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JScrollPane scrlClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}

