/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

//imports de clases
import Clases.Departamento;
import Clases.AlmacenDatos;
import Clases.Proyecto;
//imports para popup de añadido
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
//imports para modo oscuro
import java.awt.Color;
import java.awt.Font;
import javax.swing.JPanel;
//imports para tabla
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author LUCAS
 */
public class pnlDepartamentos extends javax.swing.JPanel {

    private AlmacenDatos ad;
    private Proyecto proyecto;
    private JPanel pnlCuerpo;

    public pnlDepartamentos(AlmacenDatos ad, Proyecto proyecto, JPanel pnlCuerpo) {
        initComponents();

        this.ad = ad;
        this.proyecto = proyecto;
        this.pnlCuerpo = pnlCuerpo;

        lblDepartamentos.setText("Departamentos - " + proyecto.getNombreProyecto());
        btnNuevoDepartamento.setText("Nuevo Departamento +");

        configurarTabla();
        aplicarTemaOscuro();
        cargarTabla();

        txtBuscar.addActionListener(e -> buscarDepartamentos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDepartamentos = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevoDepartamento = new javax.swing.JButton();
        scrlDepartamentos = new javax.swing.JScrollPane();
        tblDepartamentos = new javax.swing.JTable();

        setBackground(new java.awt.Color(18, 18, 24));

        lblDepartamentos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblDepartamentos.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartamentos.setText(".");

        lblBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar:");

        txtBuscar.setBackground(new java.awt.Color(30, 30, 40));
        txtBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(45, 45, 55));
        btnBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevoDepartamento.setBackground(new java.awt.Color(45, 45, 55));
        btnNuevoDepartamento.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNuevoDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoDepartamento.setText("Nuevo Empleado +");
        btnNuevoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDepartamentoActionPerformed(evt);
            }
        });

        scrlDepartamentos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        tblDepartamentos.setBackground(new java.awt.Color(45, 45, 45));
        tblDepartamentos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Usuario", "Contraseña", "Rol"
            }
        ));
        tblDepartamentos.getTableHeader().setResizingAllowed(false);
        tblDepartamentos.getTableHeader().setReorderingAllowed(false);
        scrlDepartamentos.setViewportView(tblDepartamentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevoDepartamento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDepartamentos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrlDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDepartamentos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevoDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDepartamentoActionPerformed
        abrirFormularioNuevoDepartamento();
    }//GEN-LAST:event_btnNuevoDepartamentoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarDepartamentos();
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void configurarTabla() {
    DefaultTableModel modelo = new DefaultTableModel(new Object[][]{},new String[]{"Código", "Piso", "N° Depa", "Área m²", "Dorm.","Baños", "Tipo", "Precio", "Estado", "Ubicación"}) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    tblDepartamentos.setModel(modelo);
   }

private void cargarTabla() {
    cargarTabla("");
}

private void buscarDepartamentos() {
    String textoBusqueda = txtBuscar.getText().trim();
    cargarTabla(textoBusqueda);
}

private void cargarTabla(String filtro) {
    DefaultTableModel modelo = (DefaultTableModel) tblDepartamentos.getModel();
    modelo.setRowCount(0);

    if (proyecto == null) {
        return;
    }

    String busqueda = filtro.toLowerCase();
    Departamento[] departamentos = proyecto.getDepartamentos();

    for (int i = 0; i < proyecto.getContadorDepartamentos(); i++) {
        Departamento dep = departamentos[i];

        if (dep != null) {
            String codigo = dep.getCodigoUnico();
            String piso = String.valueOf(dep.getNumPiso());
            String numero = String.valueOf(dep.getNumDepa());
            String tipo = dep.getTipo();
            String estado = dep.getEstado();
            String ubicacion = dep.getUbicacion();

            boolean coincide =
                    busqueda.isEmpty()
                    || codigo.toLowerCase().contains(busqueda)
                    || piso.contains(busqueda)
                    || numero.contains(busqueda)
                    || tipo.toLowerCase().contains(busqueda)
                    || estado.toLowerCase().contains(busqueda)
                    || ubicacion.toLowerCase().contains(busqueda);

            if (coincide) {
                modelo.addRow(new Object[]{
                    dep.getCodigoUnico(),
                    dep.getNumPiso(),
                    dep.getNumDepa(),
                    dep.getAreaM2(),
                    dep.getNumDormitorios(),
                    dep.getNumBanos(),
                    dep.getTipo(),
                    dep.getPrecioVenta(),
                    dep.getEstado(),
                    dep.getUbicacion()
                });
            }
        }
    }
}

    private void abrirFormularioNuevoDepartamento() {
        if (proyecto == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: no se encontró el proyecto seleccionado.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (proyecto.getContadorDepartamentos() >= proyecto.getDepartamentos().length) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pueden agregar más departamentos a este proyecto.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        JTextField txtCodigo = new JTextField();
        JTextField txtPiso = new JTextField();
        JTextField txtNumDepa = new JTextField();
        JTextField txtArea = new JTextField();
        JTextField txtDormitorios = new JTextField();
        JTextField txtBanos = new JTextField();
        JTextField txtPrecio = new JTextField();
        JTextField txtUbicacion = new JTextField();

        JComboBox<String> cmbTipo = new JComboBox<>(new String[]{
            "Flat", "Duplex", "Penthouse", "Loft"
        });

        Object[] formulario = {
            "Código único:", txtCodigo,
            "Piso:", txtPiso,
            "Número de departamento:", txtNumDepa,
            "Área m²:", txtArea,
            "Dormitorios:", txtDormitorios,
            "Baños:", txtBanos,
            "Tipo:", cmbTipo,
            "Precio de venta:", txtPrecio,
            "Ubicación:", txtUbicacion
        };

        int opcion = JOptionPane.showConfirmDialog(
                this,
                formulario,
                "Nuevo Departamento",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String codigo = txtCodigo.getText().trim();
            String pisoTexto = txtPiso.getText().trim();
            String numDepaTexto = txtNumDepa.getText().trim();
            String areaTexto = txtArea.getText().trim();
            String dormitoriosTexto = txtDormitorios.getText().trim();
            String banosTexto = txtBanos.getText().trim();
            String tipo = cmbTipo.getSelectedItem().toString();
            String precioTexto = txtPrecio.getText().trim();
            String ubicacion = txtUbicacion.getText().trim();

            if (codigo.isEmpty() || pisoTexto.isEmpty() || numDepaTexto.isEmpty()
                    || areaTexto.isEmpty() || dormitoriosTexto.isEmpty()
                    || banosTexto.isEmpty() || precioTexto.isEmpty()
                    || ubicacion.isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            try {
                int piso = Integer.parseInt(pisoTexto);
                int numDepa = Integer.parseInt(numDepaTexto);
                double area = Double.parseDouble(areaTexto);
                int dormitorios = Integer.parseInt(dormitoriosTexto);
                int banos = Integer.parseInt(banosTexto);
                double precio = Double.parseDouble(precioTexto);

                Departamento nuevo = new Departamento(
                        codigo,
                        piso,
                        numDepa,
                        area,
                        dormitorios,
                        banos,
                        tipo,
                        precio,
                        ubicacion
                );

                proyecto.registrarDepartamento(nuevo);
                cargarTabla();

                JOptionPane.showMessageDialog(
                        this,
                        "Departamento agregado correctamente."
                );

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Piso, número, área, dormitorios, baños y precio deben ser numéricos.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }
    
    private void aplicarTemaOscuro() {
        Color fondoTabla = new Color(45, 45, 45);
        Color fondoHeader = new Color(35, 35, 35);
        Color texto = Color.WHITE;
        Color seleccion = new Color(0, 120, 215);
        Color grid = new Color(70, 70, 70);
        txtBuscar.setForeground(Color.WHITE);
        txtBuscar.setCaretColor(Color.WHITE);
        tblDepartamentos.setOpaque(true);
        tblDepartamentos.setFillsViewportHeight(true);
        tblDepartamentos.setBackground(fondoTabla);
        tblDepartamentos.setForeground(texto);
        tblDepartamentos.setGridColor(grid);
        tblDepartamentos.setSelectionBackground(seleccion);
        tblDepartamentos.setSelectionForeground(texto);
        tblDepartamentos.setRowHeight(26);
        scrlDepartamentos.setBackground(fondoTabla);
        scrlDepartamentos.getViewport().setOpaque(true);
        scrlDepartamentos.getViewport().setBackground(fondoTabla);
        scrlDepartamentos.setBorder(javax.swing.BorderFactory.createLineBorder(grid));
        JTableHeader header = tblDepartamentos.getTableHeader();
        header.setOpaque(true);
        header.setBackground(fondoHeader);
        header.setForeground(texto);
        header.setFont(new Font("Calibri", Font.BOLD, 12));
        header.setReorderingAllowed(false);
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(fondoHeader);
                c.setForeground(texto);
                c.setFont(new Font("Calibri", Font.BOLD, 12));

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                setHorizontalAlignment(CENTER);

                return c;
            }
        });

        tblDepartamentos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table,
                    Object value,boolean isSelected,boolean hasFocus,int row,int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value,isSelected,hasFocus,row,column);

                if (isSelected) {
                    c.setBackground(seleccion);
                    c.setForeground(texto);
                } else {
                    c.setBackground(fondoTabla);
                    c.setForeground(texto);
                }

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                return c;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevoDepartamento;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDepartamentos;
    private javax.swing.JScrollPane scrlDepartamentos;
    private javax.swing.JTable tblDepartamentos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}

