/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

//imports para apartado de departamentos
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JPanel;
//imports para popup de añadido
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
//imports de modo oscuro
import java.awt.Color;
import java.awt.Font;
//imports de tabla
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
//imports de clases
import Clases.AlmacenDatos;
import Clases.Proyecto;

/**
 *
 * @author LUCAS
 */
public class pnlProyectos extends javax.swing.JPanel {
    private AlmacenDatos ad;
    private JPanel pnlCuerpo;
    private ArrayList<Proyecto> proyectosMostrados = new ArrayList<>();
    public pnlProyectos(AlmacenDatos ad, JPanel pnlCuerpo) {
        initComponents();
        this.ad = ad;
        this.pnlCuerpo = pnlCuerpo;

        aplicarTemaOscuro();
        cargarTabla();

        tblProyectos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                abrirDepartamentosSiCorresponde(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProyectos = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevoProyecto = new javax.swing.JButton();
        scrlProyectos = new javax.swing.JScrollPane();
        tblProyectos = new javax.swing.JTable();

        setBackground(new java.awt.Color(18, 18, 24));

        lblProyectos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblProyectos.setForeground(new java.awt.Color(255, 255, 255));
        lblProyectos.setText("Proyectos");

        lblBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar:");

        txtBuscar.setBackground(new java.awt.Color(30, 30, 40));
        txtBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(45, 45, 55));
        btnBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevoProyecto.setBackground(new java.awt.Color(45, 45, 55));
        btnNuevoProyecto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNuevoProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProyecto.setText("Nuevo Proyecto +");
        btnNuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProyectoActionPerformed(evt);
            }
        });

        scrlProyectos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        tblProyectos.setBackground(new java.awt.Color(45, 45, 45));
        tblProyectos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Distrito", "N. Pisos", "Inicio", "Entrega", "Estado", "Deps."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProyectos.getTableHeader().setResizingAllowed(false);
        tblProyectos.getTableHeader().setReorderingAllowed(false);
        scrlProyectos.setViewportView(tblProyectos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevoProyecto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProyectos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrlProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProyectos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevoProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProyectoActionPerformed
        abrirFormularioNuevoProyecto();
    }//GEN-LAST:event_btnNuevoProyectoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarProyectos();
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void cargarTabla() {
    cargarTabla("");
    }

    private void buscarProyectos() {
        String textoBusqueda = txtBuscar.getText().trim();
        cargarTabla(textoBusqueda);
    }
    
    private void abrirFormularioNuevoProyecto() {
        if (ad == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: no se encontró el almacén de datos.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        JTextField txtNombre = new JTextField();
        JTextField txtDireccion = new JTextField();
        JTextField txtDistrito = new JTextField();
        JTextField txtPisos = new JTextField();
        JTextField txtInicio = new JTextField();
        JTextField txtEntrega = new JTextField();

        JComboBox<String> cmbEstado = new JComboBox<>(new String[]{
            "En planos",
            "En construcción",
            "Terminado",
            "Cancelado"
        });

        Object[] formulario = {
            "Nombre del proyecto:", txtNombre,
            "Dirección:", txtDireccion,
            "Distrito:", txtDistrito,
            "Número de pisos:", txtPisos,
            "Fecha inicio:", txtInicio,
            "Fecha entrega:", txtEntrega,
            "Estado:", cmbEstado
        };

        int opcion = JOptionPane.showConfirmDialog(
                this,
                formulario,
                "Nuevo Proyecto",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String nombre = txtNombre.getText().trim();
            String direccion = txtDireccion.getText().trim();
            String distrito = txtDistrito.getText().trim();
            String pisosTexto = txtPisos.getText().trim();
            String inicio = txtInicio.getText().trim();
            String entrega = txtEntrega.getText().trim();
            String estado = cmbEstado.getSelectedItem().toString();

            if (nombre.isEmpty() || direccion.isEmpty() || distrito.isEmpty()
                    || pisosTexto.isEmpty() || inicio.isEmpty() || entrega.isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            int pisos;

            try {
                pisos = Integer.parseInt(pisosTexto);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "El número de pisos debe ser un número entero.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (pisos <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "El número de pisos debe ser mayor que 0.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (ad.getContProyectos() >= ad.getProyectos().length) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se pueden agregar más proyectos.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            Proyecto nuevoProyecto = new Proyecto(
                    nombre,
                    direccion,
                    distrito,
                    pisos,
                    inicio,
                    entrega,
                    estado
            );

            ad.agregarProyecto(nuevoProyecto);
            cargarTabla();

            JOptionPane.showMessageDialog(
                    this,
                    "Proyecto agregado correctamente."
            );
        }
    }
    
    private void cargarTabla(String filtro) {
        DefaultTableModel modelo = (DefaultTableModel) tblProyectos.getModel();

        modelo.setRowCount(0);
        proyectosMostrados.clear();

        if (ad == null) {
            return;
        }

        String busqueda = filtro.toLowerCase();

        Proyecto[] proyectos = ad.getProyectos();

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                String nombre = proy.getNombreProyecto();
                String direccion = proy.getDireccion();
                String distrito = proy.getDistrito();
                String estado = proy.getEstadoProyecto();

                boolean coincide =
                        busqueda.isEmpty()
                        || nombre.toLowerCase().contains(busqueda)
                        || direccion.toLowerCase().contains(busqueda)
                        || distrito.toLowerCase().contains(busqueda)
                        || estado.toLowerCase().contains(busqueda);

                if (coincide) {
                    proyectosMostrados.add(proy);

                    modelo.addRow(new Object[]{
                        proy.getNombreProyecto(),
                        proy.getDireccion(),
                        proy.getDistrito(),
                        proy.getNumeroPisos(),
                        proy.getFechaInicioObra(),
                        proy.getFechaEstimadaEntrega(),
                        proy.getEstadoProyecto(),
                        proy.getContadorDepartamentos()
                    });
                }
            }
        }
    }
      
    private void aplicarTemaOscuro() {
        Color fondoTabla = new Color(45, 45, 45);
        Color fondoHeader = new Color(35, 35, 35);
        Color texto = Color.WHITE;
        Color seleccion = new Color(0, 120, 215);
        Color grid = new Color(70, 70, 70);
        txtBuscar.setForeground(Color.WHITE);
        txtBuscar.setCaretColor(Color.WHITE);
        tblProyectos.setOpaque(true);
        tblProyectos.setFillsViewportHeight(true);
        tblProyectos.setBackground(fondoTabla);
        tblProyectos.setForeground(texto);
        tblProyectos.setGridColor(grid);
        tblProyectos.setSelectionBackground(seleccion);
        tblProyectos.setSelectionForeground(texto);
        tblProyectos.setRowHeight(26);
        scrlProyectos.setBackground(fondoTabla);
        scrlProyectos.getViewport().setOpaque(true);
        scrlProyectos.getViewport().setBackground(fondoTabla);
        scrlProyectos.setBorder(javax.swing.BorderFactory.createLineBorder(grid));
        JTableHeader header = tblProyectos.getTableHeader();
        header.setOpaque(true);
        header.setBackground(fondoHeader);
        header.setForeground(texto);
        header.setFont(new Font("Calibri", Font.BOLD, 12));
        header.setReorderingAllowed(false);
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(fondoHeader);
                c.setForeground(texto);
                c.setFont(new Font("Calibri", Font.BOLD, 12));

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                setHorizontalAlignment(CENTER);

                return c;
            }
        });

        tblProyectos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table,
                    Object value,boolean isSelected,boolean hasFocus,int row,int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value,isSelected,hasFocus,row,column);

                if (isSelected) {
                    c.setBackground(seleccion);
                    c.setForeground(texto);
                } else {
                    c.setBackground(fondoTabla);
                    c.setForeground(texto);
                }

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                return c;
            }
        });
    }

    private void abrirDepartamentosSiCorresponde(MouseEvent e) {
        int fila = tblProyectos.rowAtPoint(e.getPoint());
        int columna = tblProyectos.columnAtPoint(e.getPoint());

        if (fila == -1 || columna == -1) {
            return;
        }

        int columnaDepartamentos = 7;

        if (columna != columnaDepartamentos) {
            return;
        }

        int filaModelo = tblProyectos.convertRowIndexToModel(fila);

        if (filaModelo < 0 || filaModelo >= proyectosMostrados.size()) {
            return;
        }

        if (pnlCuerpo == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: no se encontró el panel contenedor.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        Proyecto proyectoSeleccionado = proyectosMostrados.get(filaModelo);

        pnlDepartamentos panel = new pnlDepartamentos(ad, proyectoSeleccionado, pnlCuerpo);

        pnlCuerpo.removeAll();
        pnlCuerpo.setLayout(new BorderLayout());
        pnlCuerpo.add(panel, BorderLayout.CENTER);
        pnlCuerpo.revalidate();
        pnlCuerpo.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevoProyecto;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblProyectos;
    private javax.swing.JScrollPane scrlProyectos;
    private javax.swing.JTable tblProyectos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}

