/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

//imports de clases
import Clases.AlmacenDatos;
import Clases.Departamento;
import Clases.Proyecto;
import Clases.Venta;
//imports para modo oscuro
import java.awt.Color;
//imports para tabla
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
//imports para fecha
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCAS
 */
public class pnlReportes extends javax.swing.JPanel {
    private AlmacenDatos ad;
    public pnlReportes(AlmacenDatos ad) {
        initComponents();

        this.ad = ad;

        configurarCombo();
        aplicarTemaOscuro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReportes = new javax.swing.JLabel();
        lblTipoReporte = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        scrlAcabados = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        cmbTipoReporte = new javax.swing.JComboBox<>();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();

        setBackground(new java.awt.Color(18, 18, 24));

        lblReportes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(255, 255, 255));
        lblReportes.setText("Reportes");

        lblTipoReporte.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblTipoReporte.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoReporte.setText("Tipo Reporte");

        btnGenerarReporte.setBackground(new java.awt.Color(45, 45, 55));
        btnGenerarReporte.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        scrlAcabados.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtReporte.setEditable(false);
        txtReporte.setColumns(20);
        txtReporte.setRows(5);
        scrlAcabados.setViewportView(txtReporte);

        cmbTipoReporte.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblFechaInicio.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaInicio.setText("Fecha de Inicio");

        txtFechaInicio.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblFechaFin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaFin.setText("Fecha Fin");

        txtFechaFin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlAcabados, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFechaInicio)
                                .addComponent(lblTipoReporte))
                            .addComponent(lblReportes)
                            .addComponent(lblFechaFin, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoReporte, 0, 225, Short.MAX_VALUE)
                            .addComponent(txtFechaInicio)
                            .addComponent(txtFechaFin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarReporte)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReportes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoReporte)
                    .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaFin)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlAcabados, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        generarReporte();
    }//GEN-LAST:event_btnGenerarReporteActionPerformed
    private void configurarCombo() {
        cmbTipoReporte.removeAllItems();

        cmbTipoReporte.addItem("Departamentos por proyecto");
        cmbTipoReporte.addItem("Ventas por asesor y fechas");
        cmbTipoReporte.addItem("Ingresos y saldos pendientes");
        cmbTipoReporte.addItem("Proyectos con mayor porcentaje de ventas");
    }
    
    private void generarReporte() {
        int opcion = cmbTipoReporte.getSelectedIndex();

        switch (opcion) {
            case 0:
                txtReporte.setText(reporteDepartamentosPorProyecto());
                break;

            case 1:
                txtReporte.setText(reporteVentasPorAsesorYFechas());
                break;

            case 2:
                txtReporte.setText(reporteIngresosYSaldos());
                break;

            case 3:
                txtReporte.setText(reporteProyectosMayorPorcentajeVentas());
                break;

            default:
                txtReporte.setText("Seleccione un tipo de reporte.");
                break;
        }
    }
    
    private String reporteDepartamentosPorProyecto() {
        String reporte = "";

        reporte += "REPORTE DE DEPARTAMENTOS POR PROYECTO\n";
        reporte += "=====================================\n\n";

        if (ad == null || ad.getContProyectos() == 0) {
            return reporte + "No hay proyectos registrados.";
        }

        Proyecto[] proyectos = ad.getProyectos();

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                int disponibles = 0;
                int reservados = 0;
                int vendidos = 0;

                Departamento[] deps = proy.getDepartamentos();

                for (int j = 0; j < proy.getContadorDepartamentos(); j++) {
                    Departamento dep = deps[j];

                    if (dep != null) {
                        if (dep.getEstado().equalsIgnoreCase("Disponible")) {
                            disponibles++;
                        } else if (dep.getEstado().equalsIgnoreCase("Reservado")) {
                            reservados++;
                        } else if (dep.getEstado().equalsIgnoreCase("Vendido")) {
                            vendidos++;
                        }
                    }
                }

                reporte += "Proyecto: " + proy.getNombreProyecto() + "\n";
                reporte += "Distrito: " + proy.getDistrito() + "\n";
                reporte += "Disponibles: " + disponibles + "\n";
                reporte += "Reservados: " + reservados + "\n";
                reporte += "Vendidos: " + vendidos + "\n";
                reporte += "Total departamentos: " + proy.getContadorDepartamentos() + "\n";
                reporte += "-------------------------------------\n\n";
            }
        }

        return reporte;
    }

    private String reporteVentasPorAsesorYFechas() {
        String reporte = "";

        reporte += "REPORTE DE VENTAS POR ASESOR Y RANGO DE FECHAS\n";
        reporte += "===============================================\n\n";

        if (ad == null || ad.getContVentas() == 0) {
            return reporte + "No hay ventas registradas.";
        }

        String fechaInicioTexto = txtFechaInicio.getText().trim();
        String fechaFinTexto = txtFechaFin.getText().trim();

        if (fechaInicioTexto.isEmpty() || fechaFinTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese fecha inicio y fecha fin en formato dd/MM/yyyy.",
                    "Fechas requeridas",
                    JOptionPane.WARNING_MESSAGE
            );
            return "";
        }

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        formato.setLenient(false);

        try {
            Date fechaInicio = formato.parse(fechaInicioTexto);
            Date fechaFin = formato.parse(fechaFinTexto);

            if (fechaInicio.after(fechaFin)) {
                return "La fecha inicio no puede ser mayor que la fecha fin.";
            }

            Venta[] ventas = ad.getVentas();
            int contador = 0;
            double totalVentas = 0;

            for (int i = 0; i < ad.getContVentas(); i++) {
                Venta venta = ventas[i];

                if (venta != null) {
                    Date fechaVenta = formato.parse(venta.getFechaVenta());

                    boolean dentroRango =
                            !fechaVenta.before(fechaInicio)
                            && !fechaVenta.after(fechaFin);

                    if (dentroRango) {
                        contador++;
                        totalVentas += venta.getDepartamento().calcularPrecioFinal();

                        reporte += "Asesor: "
                                + venta.getAsesor().getNombres()
                                + " "
                                + venta.getAsesor().getApellidos()
                                + "\n";

                        reporte += "Cliente: "
                                + venta.getCliente().getNombres()
                                + " "
                                + venta.getCliente().getApellidos()
                                + "\n";

                        reporte += "DNI Cliente: " + venta.getCliente().getDni() + "\n";
                        reporte += "Departamento: " + venta.getDepartamento().getNumDepa() + "\n";
                        reporte += "Fecha venta: " + venta.getFechaVenta() + "\n";
                        reporte += "Modalidad: " + venta.getModalidadPago() + "\n";
                        reporte += "Precio final: S/ "
                                + String.format("%.2f", venta.getDepartamento().calcularPrecioFinal())
                                + "\n";
                        reporte += "-----------------------------------------------\n\n";
                    }
                }
            }

            reporte += "TOTAL DE VENTAS EN RANGO: " + contador + "\n";
            reporte += "MONTO TOTAL VENDIDO: S/ " + String.format("%.2f", totalVentas) + "\n";

            if (contador == 0) {
                reporte += "\nNo se encontraron ventas en ese rango de fechas.";
            }

            return reporte;

        } catch (Exception e) {
            return "Error: las fechas deben estar en formato dd/MM/yyyy.";
        }
    }
    
    private String reporteIngresosYSaldos() {
        String reporte = "";

        reporte += "REPORTE DE INGRESOS Y SALDOS PENDIENTES\n";
        reporte += "=======================================\n\n";

        if (ad == null || ad.getContVentas() == 0) {
            return reporte + "No hay ventas registradas.";
        }

        double ingresosTotales = 0;
        double saldosPendientes = 0;

        Venta[] ventas = ad.getVentas();

        for (int i = 0; i < ad.getContVentas(); i++) {
            Venta venta = ventas[i];

            if (venta != null) {
                ingresosTotales += venta.getMontoPagado();
                saldosPendientes += venta.calcularSaldoPendiente();

                reporte += "Cliente: "
                        + venta.getCliente().getNombres()
                        + " "
                        + venta.getCliente().getApellidos()
                        + "\n";

                reporte += "Departamento: " + venta.getDepartamento().getNumDepa() + "\n";
                reporte += "Precio final: S/ "
                        + String.format("%.2f", venta.getDepartamento().calcularPrecioFinal())
                        + "\n";
                reporte += "Monto pagado: S/ "
                        + String.format("%.2f", venta.getMontoPagado())
                        + "\n";
                reporte += "Saldo pendiente: S/ "
                        + String.format("%.2f", venta.calcularSaldoPendiente())
                        + "\n";
                reporte += "---------------------------------------\n\n";
            }
        }

        reporte += "INGRESOS TOTALES: S/ " + String.format("%.2f", ingresosTotales) + "\n";
        reporte += "SALDO TOTAL PENDIENTE: S/ " + String.format("%.2f", saldosPendientes) + "\n";

        return reporte;
    }
    
    private String reporteProyectosMayorPorcentajeVentas() {
        String reporte = "";

        reporte += "REPORTE DE PROYECTOS CON MAYOR PORCENTAJE DE VENTAS\n";
        reporte += "====================================================\n\n";

        if (ad == null || ad.getContProyectos() == 0) {
            return reporte + "No hay proyectos registrados.";
        }

        Proyecto[] proyectos = ad.getProyectos();

        double mayorPorcentaje = -1;

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                double porcentaje = proy.calcularPorcentajeVentas();

                if (porcentaje > mayorPorcentaje) {
                    mayorPorcentaje = porcentaje;
                }
            }
        }

        reporte += "Mayor porcentaje encontrado: "
                + String.format("%.2f", mayorPorcentaje)
                + "%\n\n";

        reporte += "Proyecto(s) con mayor porcentaje:\n";
        reporte += "----------------------------------\n";

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                double porcentaje = proy.calcularPorcentajeVentas();

                if (porcentaje == mayorPorcentaje) {
                    reporte += "Proyecto: " + proy.getNombreProyecto() + "\n";
                    reporte += "Distrito: " + proy.getDistrito() + "\n";
                    reporte += "Departamentos: " + proy.getContadorDepartamentos() + "\n";
                    reporte += "Porcentaje de ventas: "
                            + String.format("%.2f", porcentaje)
                            + "%\n";
                    reporte += "----------------------------------\n";
                }
            }
        }

        reporte += "\nDETALLE DE TODOS LOS PROYECTOS\n";
        reporte += "------------------------------\n";

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                reporte += proy.getNombreProyecto()
                        + " → "
                        + String.format("%.2f", proy.calcularPorcentajeVentas())
                        + "% vendido\n";
            }
        }

        return reporte;
    }
    
    private void aplicarTemaOscuro() {
        setBackground(new Color(18, 18, 24));

        txtReporte.setBackground(new Color(30, 30, 40));
        txtReporte.setForeground(Color.WHITE);
        txtReporte.setCaretColor(Color.WHITE);

        txtFechaInicio.setBackground(new Color(30, 30, 40));
        txtFechaInicio.setForeground(Color.WHITE);
        txtFechaInicio.setCaretColor(Color.WHITE);

        txtFechaFin.setBackground(new Color(30, 30, 40));
        txtFechaFin.setForeground(Color.WHITE);
        txtFechaFin.setCaretColor(Color.WHITE);

        btnGenerarReporte.setBackground(new Color(45, 45, 55));
        btnGenerarReporte.setForeground(Color.WHITE);

        cmbTipoReporte.setBackground(new Color(45, 45, 55));
        cmbTipoReporte.setForeground(Color.WHITE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JComboBox<String> cmbTipoReporte;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTipoReporte;
    private javax.swing.JScrollPane scrlAcabados;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextArea txtReporte;
    // End of variables declaration//GEN-END:variables
}

