/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

//imports de clases
import Clases.AlmacenDatos;
import Clases.Cliente;
import Clases.Departamento;
import Clases.Proyecto;
import Clases.Reserva;
//imports para popup de añadido
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import java.util.ArrayList;
//imports para modo oscuro
import java.awt.Color;
import java.awt.Font;
//imports para tabla
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author LUCAS
 */
public class pnlReservas extends javax.swing.JPanel {
    private AlmacenDatos ad;
    public pnlReservas(AlmacenDatos ad) {
        initComponents();
        this.ad = ad;
        configurarTabla();
        aplicarTemaOscuro();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReservas = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevaReserva = new javax.swing.JButton();
        scrlReserva = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();

        setBackground(new java.awt.Color(18, 18, 24));

        lblReservas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblReservas.setForeground(new java.awt.Color(255, 255, 255));
        lblReservas.setText("Reservas");

        lblBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar:");

        txtBuscar.setBackground(new java.awt.Color(30, 30, 40));
        txtBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(45, 45, 55));
        btnBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevaReserva.setBackground(new java.awt.Color(45, 45, 55));
        btnNuevaReserva.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNuevaReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaReserva.setText("Nuevo Reservas +");
        btnNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaReservaActionPerformed(evt);
            }
        });

        scrlReserva.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        tblReservas.setBackground(new java.awt.Color(45, 45, 45));
        tblReservas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Usuario", "Contraseña", "Rol"
            }
        ));
        tblReservas.getTableHeader().setResizingAllowed(false);
        tblReservas.getTableHeader().setReorderingAllowed(false);
        scrlReserva.setViewportView(tblReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevaReserva))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReservas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrlReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReservas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevaReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaReservaActionPerformed
        abrirFormularioNuevaReserva();
    }//GEN-LAST:event_btnNuevaReservaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarReservas();
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void configurarTabla() {
     DefaultTableModel modelo = new DefaultTableModel(
             new Object[][]{},
             new String[]{
                 "DNI Cliente",
                 "Cliente",
                 "Proyecto",
                 "Código Depa",
                 "N° Depa",
                 "Monto",
                 "Vigencia",
                 "Vigente",
                 "Estado Depa"
             }
     ) {
         @Override
         public boolean isCellEditable(int row, int column) {
             return false;
         }
     };

     tblReservas.setModel(modelo);
    }   

    private void cargarTabla() {
        cargarTabla("");
    }

    private void buscarReservas() {
        String textoBusqueda = txtBuscar.getText().trim();
        cargarTabla(textoBusqueda);
    }

    private void cargarTabla(String filtro) {
        DefaultTableModel modelo = (DefaultTableModel) tblReservas.getModel();
        modelo.setRowCount(0);

        if (ad == null) {
            return;
        }

        String busqueda = filtro.toLowerCase();

        Reserva[] reservas = ad.getReservas();

        for (int i = 0; i < ad.getContReservas(); i++) {
            Reserva res = reservas[i];

            if (res != null) {
                Cliente cli = res.getCliente();
                Departamento dep = res.getDepartamento();
                String proyecto = buscarNombreProyectoPorDepartamento(dep);

                String dni = cli.getDni();
                String cliente = cli.getNombres() + " " + cli.getApellidos();
                String codigoDepa = dep.getCodigoUnico();
                String numDepa = String.valueOf(dep.getNumDepa());
                String estadoDepa = dep.getEstado();

                boolean coincide =
                        busqueda.isEmpty()
                        || dni.toLowerCase().contains(busqueda)
                        || cliente.toLowerCase().contains(busqueda)
                        || proyecto.toLowerCase().contains(busqueda)
                        || codigoDepa.toLowerCase().contains(busqueda)
                        || numDepa.contains(busqueda)
                        || estadoDepa.toLowerCase().contains(busqueda);

                if (coincide) {
                    modelo.addRow(new Object[]{
                        cli.getDni(),
                        cliente,
                        proyecto,
                        dep.getCodigoUnico(),
                        dep.getNumDepa(),
                        res.getMontoPagado(),
                        res.getFechaVigencia(),
                        res.isVigente() ? "Sí" : "No",
                        dep.getEstado()
                    });
                }
            }
        }
    }
    
    private String buscarNombreProyectoPorDepartamento(Departamento departamento) {
        if (ad == null || departamento == null) {
            return "";
        }

        Proyecto[] proyectos = ad.getProyectos();

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                Departamento[] deps = proy.getDepartamentos();

                for (int j = 0; j < proy.getContadorDepartamentos(); j++) {
                    if (deps[j] == departamento) {
                        return proy.getNombreProyecto();
                    }
                }
            }
        }

        return "";
    }
    
    private void abrirFormularioNuevaReserva() {
        if (ad == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: no se encontró el almacén de datos.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (ad.getContClientes() == 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Primero debes registrar al menos un cliente.",
                    "Sin clientes",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (ad.getContReservas() >= ad.getReservas().length) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pueden agregar más reservas.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        ArrayList<Cliente> listaClientes = new ArrayList<>();
        JComboBox<String> cmbClientes = new JComboBox<>();

        for (int i = 0; i < ad.getContClientes(); i++) {
            Cliente cli = ad.getClientes()[i];

            if (cli != null) {
                listaClientes.add(cli);
                cmbClientes.addItem(cli.getDni() + " - " + cli.getNombres() + " " + cli.getApellidos());
            }
        }

        ArrayList<Departamento> listaDepartamentos = new ArrayList<>();
        JComboBox<String> cmbDepartamentos = new JComboBox<>();

        Proyecto[] proyectos = ad.getProyectos();

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                Departamento[] deps = proy.getDepartamentos();

                for (int j = 0; j < proy.getContadorDepartamentos(); j++) {
                    Departamento dep = deps[j];

                    if (dep != null && dep.getEstado().equalsIgnoreCase("Disponible")) {
                        listaDepartamentos.add(dep);
                        cmbDepartamentos.addItem(
                                proy.getNombreProyecto()
                                + " | Depa " + dep.getNumDepa()
                                + " | " + dep.getCodigoUnico()
                                + " | S/ " + dep.getPrecioVenta()
                        );
                    }
                }
            }
        }

        if (listaDepartamentos.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay departamentos disponibles para reservar.",
                    "Sin departamentos disponibles",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        JTextField txtMonto = new JTextField();
        JTextField txtFechaVigencia = new JTextField();

        Object[] formulario = {
            "Cliente:", cmbClientes,
            "Departamento:", cmbDepartamentos,
            "Monto pagado:", txtMonto,
            "Fecha vigencia:", txtFechaVigencia
        };

        int opcion = JOptionPane.showConfirmDialog(
                this,
                formulario,
                "Nueva Reserva",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String montoTexto = txtMonto.getText().trim();
            String fechaVigencia = txtFechaVigencia.getText().trim();

            if (montoTexto.isEmpty() || fechaVigencia.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            double monto;

            try {
                monto = Double.parseDouble(montoTexto);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "El monto debe ser numérico.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (monto <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "El monto debe ser mayor que 0.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            Cliente clienteSeleccionado = listaClientes.get(cmbClientes.getSelectedIndex());
            Departamento departamentoSeleccionado = listaDepartamentos.get(cmbDepartamentos.getSelectedIndex());

            Reserva nueva = new Reserva(
                    clienteSeleccionado,
                    departamentoSeleccionado,
                    monto,
                    fechaVigencia,
                    true
            );

            boolean registrada = nueva.registrarReserva();

            if (!registrada) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo reservar. El departamento ya no está disponible.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            Reserva[] reservas = ad.getReservas();
            reservas[ad.getContReservas()] = nueva;
            ad.setContReservas(ad.getContReservas() + 1);

            cargarTabla();

            JOptionPane.showMessageDialog(
                    this,
                    "Reserva registrada correctamente."
            );
        }
    }
    
    private void aplicarTemaOscuro() {
        Color fondoTabla = new Color(45, 45, 45);
        Color fondoHeader = new Color(35, 35, 35);
        Color texto = Color.WHITE;
        Color seleccion = new Color(0, 120, 215);
        Color grid = new Color(70, 70, 70);
        txtBuscar.setForeground(Color.WHITE);
        txtBuscar.setCaretColor(Color.WHITE);
        tblReservas.setOpaque(true);
        tblReservas.setFillsViewportHeight(true);
        tblReservas.setBackground(fondoTabla);
        tblReservas.setForeground(texto);
        tblReservas.setGridColor(grid);
        tblReservas.setSelectionBackground(seleccion);
        tblReservas.setSelectionForeground(texto);
        tblReservas.setRowHeight(26);
        scrlReserva.setBackground(fondoTabla);
        scrlReserva.getViewport().setOpaque(true);
        scrlReserva.getViewport().setBackground(fondoTabla);
        scrlReserva.setBorder(javax.swing.BorderFactory.createLineBorder(grid));
        JTableHeader header = tblReservas.getTableHeader();
        header.setOpaque(true);
        header.setBackground(fondoHeader);
        header.setForeground(texto);
        header.setFont(new Font("Calibri", Font.BOLD, 12));
        header.setReorderingAllowed(false);
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(fondoHeader);
                c.setForeground(texto);
                c.setFont(new Font("Calibri", Font.BOLD, 12));

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                setHorizontalAlignment(CENTER);

                return c;
            }
        });

        tblReservas.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table,
                    Object value,boolean isSelected,boolean hasFocus,int row,int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value,isSelected,hasFocus,row,column);

                if (isSelected) {
                    c.setBackground(seleccion);
                    c.setForeground(texto);
                } else {
                    c.setBackground(fondoTabla);
                    c.setForeground(texto);
                }

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                return c;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevaReserva;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblReservas;
    private javax.swing.JScrollPane scrlReserva;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}

