/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

//imports de clases
import Clases.AlmacenDatos;
import Clases.AsesorVenta;
import Clases.Cliente;
import Clases.Departamento;
import Clases.Proyecto;
import Clases.Reserva;
import Clases.Venta;
//imports para popup de añadido
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
//imports para modo oscuro
import java.awt.Color;
import java.awt.Font;
//imports para tabla
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author LUCAS
 */
public class pnlVentas extends javax.swing.JPanel {
    private AlmacenDatos ad;
    private AsesorVenta asesorActual;
    public pnlVentas(AlmacenDatos ad, AsesorVenta asesorActual) {
        initComponents();

        this.ad = ad;
        this.asesorActual = asesorActual;

        configurarTabla();
        aplicarTemaOscuro();
        cargarTabla();

        btnBuscar.addActionListener(e -> buscarVentas());
        txtBuscar.addActionListener(e -> buscarVentas());
        btnNuevaVenta.addActionListener(e -> abrirFormularioNuevaVenta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVentas = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevaVenta = new javax.swing.JButton();
        scrlVentas = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();

        setBackground(new java.awt.Color(18, 18, 24));

        lblVentas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(255, 255, 255));
        lblVentas.setText("Ventas");

        lblBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar:");

        txtBuscar.setBackground(new java.awt.Color(30, 30, 40));
        txtBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(45, 45, 55));
        btnBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevaVenta.setBackground(new java.awt.Color(45, 45, 55));
        btnNuevaVenta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaVenta.setText("Nueva Venta +");
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });

        scrlVentas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        tblVentas.setBackground(new java.awt.Color(45, 45, 45));
        tblVentas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Usuario", "Contraseña", "Rol"
            }
        ));
        tblVentas.getTableHeader().setResizingAllowed(false);
        tblVentas.getTableHeader().setReorderingAllowed(false);
        scrlVentas.setViewportView(tblVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevaVenta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVentas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrlVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevaVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        abrirFormularioNuevaVenta();
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarVentas();
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Cliente",
                    "DNI",
                    "Proyecto",
                    "Depa",
                    "Precio",
                    "Modalidad",
                    "Fecha Venta",
                    "Inicial",
                    "Cuotas",
                    "Saldo"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblVentas.setModel(modelo);
    }

    private void cargarTabla() {
        cargarTabla("");
    }

    private void buscarVentas() {
        String textoBusqueda = txtBuscar.getText().trim();
        cargarTabla(textoBusqueda);
    }

    private void cargarTabla(String filtro) {
        DefaultTableModel modelo = (DefaultTableModel) tblVentas.getModel();
        modelo.setRowCount(0);

        if (ad == null) {
            return;
        }

        String busqueda = filtro.toLowerCase();

        Venta[] ventas = ad.getVentas();

        for (int i = 0; i < ad.getContVentas(); i++) {
            Venta venta = ventas[i];

            if (venta != null) {
                Cliente cli = venta.getCliente();
                Departamento dep = venta.getDepartamento();
                String proyecto = buscarNombreProyectoPorDepartamento(dep);

                String cliente = cli.getNombres() + " " + cli.getApellidos();
                String dni = cli.getDni();
                String depa = String.valueOf(dep.getNumDepa());
                String modalidad = venta.getModalidadPago();
                String fecha = venta.getFechaVenta();

                boolean coincide =
                        busqueda.isEmpty()
                        || cliente.toLowerCase().contains(busqueda)
                        || dni.toLowerCase().contains(busqueda)
                        || proyecto.toLowerCase().contains(busqueda)
                        || depa.contains(busqueda)
                        || modalidad.toLowerCase().contains(busqueda)
                        || fecha.toLowerCase().contains(busqueda);

                if (coincide) {
                    modelo.addRow(new Object[]{
                        cliente,
                        dni,
                        proyecto,
                        dep.getNumDepa(),
                        dep.getPrecioVenta(),
                        venta.getModalidadPago(),
                        venta.getFechaVenta(),
                        venta.getCuotaInicial(),
                        venta.getNumeroCuotas(),
                        venta.calcularSaldoPendiente()
                    });
                }
            }
        }
    }
    
    private String buscarNombreProyectoPorDepartamento(Departamento departamento) {
        if (ad == null || departamento == null) {
            return "";
        }

        Proyecto[] proyectos = ad.getProyectos();

        for (int i = 0; i < ad.getContProyectos(); i++) {
            Proyecto proy = proyectos[i];

            if (proy != null) {
                Departamento[] deps = proy.getDepartamentos();

                for (int j = 0; j < proy.getContadorDepartamentos(); j++) {
                    if (deps[j] == departamento) {
                        return proy.getNombreProyecto();
                    }
                }
            }
        }

        return "";
    }
    
    private void abrirFormularioNuevaVenta() {
        if (ad == null || asesorActual == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: no se encontró el almacén de datos o el asesor actual.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (ad.getContReservas() == 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Primero debe existir una reserva.",
                    "Sin reservas",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (ad.getContVentas() >= ad.getVentas().length) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pueden registrar más ventas.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        ArrayList<Reserva> listaReservas = new ArrayList<>();
        JComboBox<String> cmbReservas = new JComboBox<>();

        for (int i = 0; i < ad.getContReservas(); i++) {
            Reserva res = ad.getReservas()[i];

            if (res != null
                    && res.isVigente()
                    && res.getDepartamento().getEstado().equalsIgnoreCase("Reservado")) {

                Cliente cli = res.getCliente();
                Departamento dep = res.getDepartamento();
                String proyecto = buscarNombreProyectoPorDepartamento(dep);

                listaReservas.add(res);
                cmbReservas.addItem(
                        cli.getDni()
                        + " - " + cli.getNombres() + " " + cli.getApellidos()
                        + " | " + proyecto
                        + " | Depa " + dep.getNumDepa()
                        + " | S/ " + dep.getPrecioVenta()
                );
            }
        }

        if (listaReservas.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay reservas vigentes para vender.",
                    "Sin reservas disponibles",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        JComboBox<String> cmbModalidad = new JComboBox<>(new String[]{
            "Contado",
            "Cuotas Directas",
            "Crédito Hipotecario"
        });

        JTextField txtFechaVenta = new JTextField();
        JTextField txtCuotaInicial = new JTextField();
        JTextField txtNumeroCuotas = new JTextField();

        Object[] formulario = {
            "Reserva:", cmbReservas,
            "Modalidad de pago:", cmbModalidad,
            "Fecha venta:", txtFechaVenta,
            "Cuota inicial:", txtCuotaInicial,
            "Número de cuotas:", txtNumeroCuotas
        };

        int opcion = JOptionPane.showConfirmDialog(
                this,
                formulario,
                "Nueva Venta",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String modalidad = cmbModalidad.getSelectedItem().toString();
            String fechaVenta = txtFechaVenta.getText().trim();
            String cuotaTexto = txtCuotaInicial.getText().trim();
            String cuotasTexto = txtNumeroCuotas.getText().trim();

            if (fechaVenta.isEmpty() || cuotaTexto.isEmpty() || cuotasTexto.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            double cuotaInicial;
            int numeroCuotas;

            try {
                cuotaInicial = Double.parseDouble(cuotaTexto);
                numeroCuotas = Integer.parseInt(cuotasTexto);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "La cuota inicial y el número de cuotas deben ser numéricos.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (cuotaInicial < 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "La cuota inicial no puede ser negativa.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (modalidad.equalsIgnoreCase("Cuotas Directas") && numeroCuotas <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Para cuotas directas, el número de cuotas debe ser mayor que 0.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (!modalidad.equalsIgnoreCase("Cuotas Directas")) {
                numeroCuotas = 0;
            }

            Reserva reservaSeleccionada = listaReservas.get(cmbReservas.getSelectedIndex());

            Venta nueva = new Venta(
                    reservaSeleccionada,
                    asesorActual,
                    modalidad,
                    fechaVenta,
                    cuotaInicial,
                    numeroCuotas
            );

            boolean registrada = nueva.registrarVenta();

            if (!registrada) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo registrar la venta. La reserva ya no está vigente o el departamento no está reservado.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            Venta[] ventas = ad.getVentas();
            ventas[ad.getContVentas()] = nueva;
            ad.setContVentas(ad.getContVentas() + 1);

            cargarTabla();

            JOptionPane.showMessageDialog(
                    this,
                    "Venta registrada correctamente."
            );
        }
    }
    
    private void aplicarTemaOscuro() {
        Color fondoTabla = new Color(45, 45, 45);
        Color fondoHeader = new Color(35, 35, 35);
        Color texto = Color.WHITE;
        Color seleccion = new Color(0, 120, 215);
        Color grid = new Color(70, 70, 70);
        txtBuscar.setForeground(Color.WHITE);
        txtBuscar.setCaretColor(Color.WHITE);
        tblVentas.setOpaque(true);
        tblVentas.setFillsViewportHeight(true);
        tblVentas.setBackground(fondoTabla);
        tblVentas.setForeground(texto);
        tblVentas.setGridColor(grid);
        tblVentas.setSelectionBackground(seleccion);
        tblVentas.setSelectionForeground(texto);
        tblVentas.setRowHeight(26);
        scrlVentas.setBackground(fondoTabla);
        scrlVentas.getViewport().setOpaque(true);
        scrlVentas.getViewport().setBackground(fondoTabla);
        scrlVentas.setBorder(javax.swing.BorderFactory.createLineBorder(grid));
        JTableHeader header = tblVentas.getTableHeader();
        header.setOpaque(true);
        header.setBackground(fondoHeader);
        header.setForeground(texto);
        header.setFont(new Font("Calibri", Font.BOLD, 12));
        header.setReorderingAllowed(false);
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(fondoHeader);
                c.setForeground(texto);
                c.setFont(new Font("Calibri", Font.BOLD, 12));

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                setHorizontalAlignment(CENTER);

                return c;
            }
        });

        tblVentas.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table,
                    Object value,boolean isSelected,boolean hasFocus,int row,int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value,isSelected,hasFocus,row,column);

                if (isSelected) {
                    c.setBackground(seleccion);
                    c.setForeground(texto);
                } else {
                    c.setBackground(fondoTabla);
                    c.setForeground(texto);
                }

                if (c instanceof javax.swing.JComponent) {
                    ((javax.swing.JComponent) c).setOpaque(true);
                }

                return c;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JScrollPane scrlVentas;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}

